import { storage } from "./storage";

interface AtomicControlSeed {
  controlId: string;
  sourceKey: string;
  legalRef: string;
  clausePath: string;
  shortTitle: string;
  obligationText: string;
  obligationVerb?: string;
  applicability: Record<string, any>;
  evidenceTypes: string[];
  testProcedure: Record<string, any>;
  domain: string;
  weight: number;
}

const NIS2_CONTROLS: AtomicControlSeed[] = [
  {
    controlId: "NIS2-20-1",
    sourceKey: "NIS2_2022_2555",
    legalRef: "Article 20(1)",
    clausePath: "Art.20.1",
    shortTitle: "Management body approval of cybersecurity measures",
    obligationText: "Management bodies of essential and important entities shall approve the cybersecurity risk-management measures taken by those entities.",
    obligationVerb: "shall approve",
    applicability: { entities: ["ALL_NIS2_ENTITIES"] },
    evidenceTypes: ["Board resolution", "Meeting minutes", "Approval record"],
    testProcedure: { method: "Review board minutes for formal approval of cybersecurity risk-management measures" },
    domain: "Governance",
    weight: 3,
  },
  {
    controlId: "NIS2-20-2",
    sourceKey: "NIS2_2022_2555",
    legalRef: "Article 20(2)",
    clausePath: "Art.20.2",
    shortTitle: "Management body cybersecurity training",
    obligationText: "Members of the management bodies shall be required to follow training to gain sufficient knowledge and skills to identify risks and assess cybersecurity risk-management practices.",
    obligationVerb: "shall follow training",
    applicability: { entities: ["ALL_NIS2_ENTITIES"] },
    evidenceTypes: ["Training records", "Certificates", "Attendance logs"],
    testProcedure: { method: "Verify training records exist for all management body members covering cybersecurity risk identification" },
    domain: "Governance",
    weight: 2,
  },
  {
    controlId: "NIS2-21-1",
    sourceKey: "NIS2_2022_2555",
    legalRef: "Article 21(1)",
    clausePath: "Art.21.1",
    shortTitle: "Appropriate cybersecurity risk-management measures",
    obligationText: "Entities shall take appropriate and proportionate technical, operational and organisational measures to manage risks posed to the security of network and information systems.",
    obligationVerb: "shall take",
    applicability: { entities: ["ALL_NIS2_ENTITIES"] },
    evidenceTypes: ["Risk management framework", "Security policy", "Technical architecture"],
    testProcedure: { method: "Review overall risk management framework for appropriateness and proportionality" },
    domain: "Risk Management",
    weight: 3,
  },
  {
    controlId: "NIS2-21-2-a",
    sourceKey: "NIS2_2022_2555",
    legalRef: "Article 21(2)(a)",
    clausePath: "Art.21.2.a",
    shortTitle: "Policies on risk analysis and information system security",
    obligationText: "Measures shall include policies on risk analysis and information system security.",
    obligationVerb: "shall include",
    applicability: { entities: ["ALL_NIS2_ENTITIES"] },
    evidenceTypes: ["Risk analysis policy", "Information security policy", "ISMS documentation"],
    testProcedure: { method: "Verify existence of documented risk analysis and IS security policies, review their completeness" },
    domain: "Risk Management",
    weight: 3,
  },
  {
    controlId: "NIS2-21-2-b",
    sourceKey: "NIS2_2022_2555",
    legalRef: "Article 21(2)(b)",
    clausePath: "Art.21.2.b",
    shortTitle: "Incident handling procedures",
    obligationText: "Measures shall include incident handling procedures and processes.",
    obligationVerb: "shall include",
    applicability: { entities: ["ALL_NIS2_ENTITIES"] },
    evidenceTypes: ["Incident response plan", "Incident handling procedure", "Escalation matrix"],
    testProcedure: { method: "Review incident handling procedures for completeness, including detection, analysis, containment, and recovery" },
    domain: "Incident Management",
    weight: 3,
  },
  {
    controlId: "NIS2-21-2-c",
    sourceKey: "NIS2_2022_2555",
    legalRef: "Article 21(2)(c)",
    clausePath: "Art.21.2.c",
    shortTitle: "Business continuity and crisis management",
    obligationText: "Measures shall include business continuity, such as backup management and disaster recovery, and crisis management.",
    obligationVerb: "shall include",
    applicability: { entities: ["ALL_NIS2_ENTITIES"] },
    evidenceTypes: ["BCP", "DR plan", "Backup policy", "Crisis management plan"],
    testProcedure: { method: "Review BCP/DR plans, verify backup procedures and crisis management arrangements" },
    domain: "Business Continuity",
    weight: 3,
  },
  {
    controlId: "NIS2-21-2-d",
    sourceKey: "NIS2_2022_2555",
    legalRef: "Article 21(2)(d)",
    clausePath: "Art.21.2.d",
    shortTitle: "Supply chain security",
    obligationText: "Measures shall include supply chain security, including security-related aspects concerning the relationships between each entity and its direct suppliers or service providers.",
    obligationVerb: "shall include",
    applicability: { entities: ["ALL_NIS2_ENTITIES"] },
    evidenceTypes: ["Supplier security policy", "Vendor risk assessments", "Supply chain agreements"],
    testProcedure: { method: "Review supplier security assessments, contractual security requirements, and supply chain risk management" },
    domain: "Supply Chain",
    weight: 3,
  },
  {
    controlId: "NIS2-21-2-e",
    sourceKey: "NIS2_2022_2555",
    legalRef: "Article 21(2)(e)",
    clausePath: "Art.21.2.e",
    shortTitle: "Security in network and information systems acquisition",
    obligationText: "Measures shall include security in network and information systems acquisition, development and maintenance, including vulnerability handling and disclosure.",
    obligationVerb: "shall include",
    applicability: { entities: ["ALL_NIS2_ENTITIES"] },
    evidenceTypes: ["Secure development policy", "Vulnerability management procedure", "Patch management records"],
    testProcedure: { method: "Review secure development lifecycle, vulnerability handling processes, and patch management" },
    domain: "Security Operations",
    weight: 2,
  },
  {
    controlId: "NIS2-21-2-f",
    sourceKey: "NIS2_2022_2555",
    legalRef: "Article 21(2)(f)",
    clausePath: "Art.21.2.f",
    shortTitle: "Cybersecurity risk-management effectiveness assessment",
    obligationText: "Measures shall include policies and procedures to assess the effectiveness of cybersecurity risk-management measures.",
    obligationVerb: "shall include",
    applicability: { entities: ["ALL_NIS2_ENTITIES"] },
    evidenceTypes: ["Audit reports", "Effectiveness assessment methodology", "KPI/metrics reports"],
    testProcedure: { method: "Verify existence of effectiveness assessment procedures, review recent assessment results and metrics" },
    domain: "Risk Management",
    weight: 2,
  },
  {
    controlId: "NIS2-21-2-g",
    sourceKey: "NIS2_2022_2555",
    legalRef: "Article 21(2)(g)",
    clausePath: "Art.21.2.g",
    shortTitle: "Basic cyber hygiene practices and training",
    obligationText: "Measures shall include basic cyber hygiene practices and cybersecurity training.",
    obligationVerb: "shall include",
    applicability: { entities: ["ALL_NIS2_ENTITIES"] },
    evidenceTypes: ["Training plan", "Awareness program", "Training completion records"],
    testProcedure: { method: "Review cyber hygiene program, training materials, and staff completion rates" },
    domain: "Governance",
    weight: 2,
  },
  {
    controlId: "NIS2-21-2-h",
    sourceKey: "NIS2_2022_2555",
    legalRef: "Article 21(2)(h)",
    clausePath: "Art.21.2.h",
    shortTitle: "Cryptography and encryption policies",
    obligationText: "Measures shall include policies and procedures regarding the use of cryptography and, where appropriate, encryption.",
    obligationVerb: "shall include",
    applicability: { entities: ["ALL_NIS2_ENTITIES"] },
    evidenceTypes: ["Cryptography policy", "Encryption standards", "Key management procedure"],
    testProcedure: { method: "Review cryptography policy, encryption implementation, and key management practices" },
    domain: "Security Operations",
    weight: 2,
  },
  {
    controlId: "NIS2-21-2-i",
    sourceKey: "NIS2_2022_2555",
    legalRef: "Article 21(2)(i)",
    clausePath: "Art.21.2.i",
    shortTitle: "Human resources security and access control",
    obligationText: "Measures shall include human resources security, access control policies and asset management.",
    obligationVerb: "shall include",
    applicability: { entities: ["ALL_NIS2_ENTITIES"] },
    evidenceTypes: ["HR security policy", "Access control policy", "Asset register"],
    testProcedure: { method: "Review HR security procedures, access control implementation, and asset management inventory" },
    domain: "Access Control",
    weight: 2,
  },
  {
    controlId: "NIS2-21-2-j",
    sourceKey: "NIS2_2022_2555",
    legalRef: "Article 21(2)(j)",
    clausePath: "Art.21.2.j",
    shortTitle: "Multi-factor authentication and secure communications",
    obligationText: "Measures shall include the use of multi-factor authentication or continuous authentication solutions, secured voice, video and text communications, and secured emergency communication systems.",
    obligationVerb: "shall include",
    applicability: { entities: ["ALL_NIS2_ENTITIES"] },
    evidenceTypes: ["MFA implementation records", "Secure communication policy", "Authentication architecture"],
    testProcedure: { method: "Verify MFA deployment, review secure communication channels, test emergency communication systems" },
    domain: "Access Control",
    weight: 2,
  },
  {
    controlId: "NIS2-23-1",
    sourceKey: "NIS2_2022_2555",
    legalRef: "Article 23(1)",
    clausePath: "Art.23.1",
    shortTitle: "Significant incident notification to CSIRT/authority",
    obligationText: "Entities shall notify, without undue delay, its CSIRT or competent authority of any significant incident.",
    obligationVerb: "shall notify",
    applicability: { entities: ["ALL_NIS2_ENTITIES"] },
    evidenceTypes: ["Notification procedure", "CSIRT contact records", "Notification templates"],
    testProcedure: { method: "Review incident notification procedure, verify CSIRT contact information is current" },
    domain: "Incident Management",
    weight: 3,
  },
  {
    controlId: "NIS2-23-4-a",
    sourceKey: "NIS2_2022_2555",
    legalRef: "Article 23(4)(a)",
    clausePath: "Art.23.4.a",
    shortTitle: "Early warning within 24 hours",
    obligationText: "An early warning shall be submitted without undue delay and in any event within 24 hours of becoming aware of the significant incident.",
    obligationVerb: "shall submit",
    applicability: { entities: ["ALL_NIS2_ENTITIES"] },
    evidenceTypes: ["Early warning template", "Notification timeline records", "Incident log"],
    testProcedure: { method: "Verify early warning process can meet 24-hour requirement, review past incident timelines" },
    domain: "Incident Management",
    weight: 3,
  },
  {
    controlId: "NIS2-23-4-b",
    sourceKey: "NIS2_2022_2555",
    legalRef: "Article 23(4)(b)",
    clausePath: "Art.23.4.b",
    shortTitle: "Incident notification within 72 hours",
    obligationText: "An incident notification shall be submitted without undue delay and in any event within 72 hours of becoming aware of the significant incident.",
    obligationVerb: "shall submit",
    applicability: { entities: ["ALL_NIS2_ENTITIES"] },
    evidenceTypes: ["Incident notification template", "Severity assessment criteria", "Notification records"],
    testProcedure: { method: "Verify notification process can meet 72-hour requirement, review notification completeness" },
    domain: "Incident Management",
    weight: 3,
  },
  {
    controlId: "NIS2-23-4-d",
    sourceKey: "NIS2_2022_2555",
    legalRef: "Article 23(4)(d)",
    clausePath: "Art.23.4.d",
    shortTitle: "Final report within one month",
    obligationText: "A final report shall be submitted not later than one month after the submission of the incident notification.",
    obligationVerb: "shall submit",
    applicability: { entities: ["ALL_NIS2_ENTITIES"] },
    evidenceTypes: ["Final report template", "Root cause analysis", "Lessons learned"],
    testProcedure: { method: "Review final report process and template, verify completeness requirements are documented" },
    domain: "Incident Management",
    weight: 2,
  },
  {
    controlId: "NIS2-25-1",
    sourceKey: "NIS2_2022_2555",
    legalRef: "Article 25(1)",
    clausePath: "Art.25.1",
    shortTitle: "Use of European cybersecurity certification schemes",
    obligationText: "Member States may require essential and important entities to use particular ICT products, services and processes that are certified under European cybersecurity certification schemes.",
    obligationVerb: "may require",
    applicability: { entities: ["ALL_NIS2_ENTITIES"] },
    evidenceTypes: ["Certification records", "Product/service inventory", "Compliance mapping"],
    testProcedure: { method: "Review ICT product and service inventory against applicable certification requirements" },
    domain: "Governance",
    weight: 1,
  },
  {
    controlId: "NIS2-29-1",
    sourceKey: "NIS2_2022_2555",
    legalRef: "Article 29(1)",
    clausePath: "Art.29.1",
    shortTitle: "Voluntary information sharing on cyber threats",
    obligationText: "Entities may exchange relevant cybersecurity information on a voluntary basis, including information relating to cyber threats, near misses, vulnerabilities, TTPs, and IoCs.",
    obligationVerb: "may exchange",
    applicability: { entities: ["ALL_NIS2_ENTITIES"] },
    evidenceTypes: ["Information sharing agreements", "Threat intelligence feeds", "Sharing platform membership"],
    testProcedure: { method: "Review participation in information sharing arrangements and threat intelligence communities" },
    domain: "Security Operations",
    weight: 1,
  },
  {
    controlId: "NIS2-21-3",
    sourceKey: "NIS2_2022_2555",
    legalRef: "Article 21(3)",
    clausePath: "Art.21.3",
    shortTitle: "All-hazards approach to risk management",
    obligationText: "Entities shall take into account vulnerabilities specific to each direct supplier and overall supply chain quality, and assess their significance for network and information system security.",
    obligationVerb: "shall take into account",
    applicability: { entities: ["ALL_NIS2_ENTITIES"] },
    evidenceTypes: ["All-hazards risk assessment", "Supply chain risk analysis", "Threat landscape assessment"],
    testProcedure: { method: "Verify risk assessment covers all hazard types including supply chain-specific vulnerabilities" },
    domain: "Risk Management",
    weight: 2,
  },
  {
    controlId: "NIS2-21-4",
    sourceKey: "NIS2_2022_2555",
    legalRef: "Article 21(4)",
    clausePath: "Art.21.4",
    shortTitle: "Compliance with standards and specifications",
    obligationText: "Entities shall, where appropriate, use European and international standards and technical specifications relevant to the security of network and information systems.",
    obligationVerb: "shall use",
    applicability: { entities: ["ALL_NIS2_ENTITIES"] },
    evidenceTypes: ["Standards compliance matrix", "ISO/IEC certifications", "Technical specifications"],
    testProcedure: { method: "Review alignment with relevant European/international standards (e.g. ISO 27001, ENISA guidelines)" },
    domain: "Governance",
    weight: 1,
  },
  {
    controlId: "NIS2-24-1",
    sourceKey: "NIS2_2022_2555",
    legalRef: "Article 24(1)",
    clausePath: "Art.24.1",
    shortTitle: "Voluntary notification of non-significant incidents",
    obligationText: "Entities may notify on a voluntary basis incidents, cyber threats and near misses that are not classified as significant.",
    obligationVerb: "may notify",
    applicability: { entities: ["ALL_NIS2_ENTITIES"] },
    evidenceTypes: ["Voluntary notification procedure", "Incident classification criteria"],
    testProcedure: { method: "Verify procedure exists for voluntary notification of non-significant incidents and near misses" },
    domain: "Incident Management",
    weight: 1,
  },
  {
    controlId: "NIS2-26-1",
    sourceKey: "NIS2_2022_2555",
    legalRef: "Article 26(1)",
    clausePath: "Art.26.1",
    shortTitle: "Supervision and enforcement for essential entities",
    obligationText: "Essential entities shall be subject to supervisory measures including on-site inspections, regular audits, targeted security audits, and ad hoc audits.",
    obligationVerb: "shall be subject",
    applicability: { entities: ["ESSENTIAL"] },
    evidenceTypes: ["Audit readiness documentation", "Previous audit reports", "Remediation tracking"],
    testProcedure: { method: "Verify audit readiness, review previous audit findings and remediation status" },
    domain: "Governance",
    weight: 2,
  },
];

const CIR_CONTROLS: AtomicControlSeed[] = [
  {
    controlId: "CIR-2024-2690-3-1",
    sourceKey: "CIR_2024_2690",
    legalRef: "Article 3(1) CIR 2024/2690",
    clausePath: "CIR.Art.3.1",
    shortTitle: "Information system security policy",
    obligationText: "Relevant entities shall establish a policy on the security of network and information systems defining the approach and objectives for the security of their network and information systems.",
    obligationVerb: "shall establish",
    applicability: { entities: ["DNS", "TLD", "CLOUD", "DC", "CDN", "MSP", "MSSP", "ONLINE_PLATFORM", "TRUST"] },
    evidenceTypes: ["Information security policy", "Policy approval records", "Policy review schedule"],
    testProcedure: { method: "Review IS policy for completeness, approval by management, and regular review schedule" },
    domain: "Governance",
    weight: 3,
  },
  {
    controlId: "CIR-2024-2690-3-2",
    sourceKey: "CIR_2024_2690",
    legalRef: "Article 3(2) CIR 2024/2690",
    clausePath: "CIR.Art.3.2",
    shortTitle: "Roles and responsibilities for network and IS security",
    obligationText: "Relevant entities shall define and assign roles and responsibilities for the security of network and information systems and establish reporting lines.",
    obligationVerb: "shall define",
    applicability: { entities: ["DNS", "TLD", "CLOUD", "DC", "CDN", "MSP", "MSSP", "ONLINE_PLATFORM", "TRUST"] },
    evidenceTypes: ["RACI matrix", "Role descriptions", "Organisational chart"],
    testProcedure: { method: "Verify documented roles/responsibilities for IS security and clear reporting lines" },
    domain: "Governance",
    weight: 2,
  },
  {
    controlId: "CIR-2024-2690-4-1",
    sourceKey: "CIR_2024_2690",
    legalRef: "Article 4(1) CIR 2024/2690",
    clausePath: "CIR.Art.4.1",
    shortTitle: "Risk management framework",
    obligationText: "Relevant entities shall establish and maintain a risk management framework to identify and address risks to the security of network and information systems.",
    obligationVerb: "shall establish",
    applicability: { entities: ["DNS", "TLD", "CLOUD", "DC", "CDN", "MSP", "MSSP", "ONLINE_PLATFORM", "TRUST"] },
    evidenceTypes: ["Risk management framework", "Risk register", "Risk assessment methodology"],
    testProcedure: { method: "Review risk management framework, methodology, and current risk register" },
    domain: "Risk Management",
    weight: 3,
  },
  {
    controlId: "CIR-2024-2690-4-2",
    sourceKey: "CIR_2024_2690",
    legalRef: "Article 4(2) CIR 2024/2690",
    clausePath: "CIR.Art.4.2",
    shortTitle: "Risk assessment methodology and criteria",
    obligationText: "The risk management framework shall define criteria for the acceptance of risks and for carrying out risk assessments, including risk identification, analysis and evaluation.",
    obligationVerb: "shall define",
    applicability: { entities: ["DNS", "TLD", "CLOUD", "DC", "CDN", "MSP", "MSSP", "ONLINE_PLATFORM", "TRUST"] },
    evidenceTypes: ["Risk acceptance criteria", "Risk assessment procedure", "Risk scoring methodology"],
    testProcedure: { method: "Verify documented risk acceptance criteria, assessment methodology including identification, analysis, evaluation" },
    domain: "Risk Management",
    weight: 2,
  },
  {
    controlId: "CIR-2024-2690-5-1",
    sourceKey: "CIR_2024_2690",
    legalRef: "Article 5(1) CIR 2024/2690",
    clausePath: "CIR.Art.5.1",
    shortTitle: "Incident handling policy and procedures",
    obligationText: "Relevant entities shall establish and implement an incident handling policy defining roles, responsibilities and procedures for detecting, analysing, containing, recovering and notifying incidents.",
    obligationVerb: "shall establish",
    applicability: { entities: ["DNS", "TLD", "CLOUD", "DC", "CDN", "MSP", "MSSP", "ONLINE_PLATFORM", "TRUST"] },
    evidenceTypes: ["Incident handling policy", "Incident response procedures", "RACI for incidents"],
    testProcedure: { method: "Review incident handling policy for defined roles, detection, analysis, containment, recovery, and notification procedures" },
    domain: "Incident Management",
    weight: 3,
  },
  {
    controlId: "CIR-2024-2690-5-2",
    sourceKey: "CIR_2024_2690",
    legalRef: "Article 5(2) CIR 2024/2690",
    clausePath: "CIR.Art.5.2",
    shortTitle: "Incident monitoring and logging",
    obligationText: "Relevant entities shall monitor and log events in their network and information systems to detect, analyse and respond to incidents in a timely manner.",
    obligationVerb: "shall monitor",
    applicability: { entities: ["DNS", "TLD", "CLOUD", "DC", "CDN", "MSP", "MSSP", "ONLINE_PLATFORM", "TRUST"] },
    evidenceTypes: ["SIEM configuration", "Log management policy", "Monitoring dashboards"],
    testProcedure: { method: "Verify event monitoring and logging capabilities, review SIEM/log management configuration" },
    domain: "Security Operations",
    weight: 2,
  },
  {
    controlId: "CIR-2024-2690-6-1",
    sourceKey: "CIR_2024_2690",
    legalRef: "Article 6(1) CIR 2024/2690",
    clausePath: "CIR.Art.6.1",
    shortTitle: "Business continuity and disaster recovery plans",
    obligationText: "Relevant entities shall establish and maintain business continuity plans and disaster recovery plans based on the results of business impact analyses.",
    obligationVerb: "shall establish",
    applicability: { entities: ["DNS", "TLD", "CLOUD", "DC", "CDN", "MSP", "MSSP", "ONLINE_PLATFORM", "TRUST"] },
    evidenceTypes: ["BCP", "DR plan", "Business impact analysis", "Recovery objectives"],
    testProcedure: { method: "Review BCP/DRP, verify they are based on BIA and include defined RTOs/RPOs" },
    domain: "Business Continuity",
    weight: 3,
  },
  {
    controlId: "CIR-2024-2690-6-2",
    sourceKey: "CIR_2024_2690",
    legalRef: "Article 6(2) CIR 2024/2690",
    clausePath: "CIR.Art.6.2",
    shortTitle: "Backup management and data restoration",
    obligationText: "Relevant entities shall ensure that backups are created, maintained and regularly tested to allow restoration of network and information systems after an incident.",
    obligationVerb: "shall ensure",
    applicability: { entities: ["DNS", "TLD", "CLOUD", "DC", "CDN", "MSP", "MSSP", "ONLINE_PLATFORM", "TRUST"] },
    evidenceTypes: ["Backup policy", "Backup schedules", "Restoration test results"],
    testProcedure: { method: "Review backup policy, verify regular backup testing and restoration capability" },
    domain: "Business Continuity",
    weight: 2,
  },
  {
    controlId: "CIR-2024-2690-7-1",
    sourceKey: "CIR_2024_2690",
    legalRef: "Article 7(1) CIR 2024/2690",
    clausePath: "CIR.Art.7.1",
    shortTitle: "Supply chain security policy",
    obligationText: "Relevant entities shall establish a supply chain security policy governing their relationships with direct suppliers and service providers.",
    obligationVerb: "shall establish",
    applicability: { entities: ["DNS", "TLD", "CLOUD", "DC", "CDN", "MSP", "MSSP", "ONLINE_PLATFORM", "TRUST"] },
    evidenceTypes: ["Supply chain security policy", "Supplier register", "Vendor assessment criteria"],
    testProcedure: { method: "Review supply chain security policy, supplier categorisation, and assessment criteria" },
    domain: "Supply Chain",
    weight: 3,
  },
  {
    controlId: "CIR-2024-2690-7-2",
    sourceKey: "CIR_2024_2690",
    legalRef: "Article 7(2) CIR 2024/2690",
    clausePath: "CIR.Art.7.2",
    shortTitle: "Supplier security requirements in contracts",
    obligationText: "Relevant entities shall include in their agreements with suppliers and service providers appropriate security requirements and obligations.",
    obligationVerb: "shall include",
    applicability: { entities: ["DNS", "TLD", "CLOUD", "DC", "CDN", "MSP", "MSSP", "ONLINE_PLATFORM", "TRUST"] },
    evidenceTypes: ["Contract templates", "Security clauses", "SLA agreements"],
    testProcedure: { method: "Review standard contract clauses for security requirements and verify inclusion in key supplier agreements" },
    domain: "Supply Chain",
    weight: 2,
  },
  {
    controlId: "CIR-2024-2690-8-1",
    sourceKey: "CIR_2024_2690",
    legalRef: "Article 8(1) CIR 2024/2690",
    clausePath: "CIR.Art.8.1",
    shortTitle: "Vulnerability handling and disclosure",
    obligationText: "Relevant entities shall establish and apply procedures for identifying, evaluating, treating and managing vulnerabilities in the network and information systems they use.",
    obligationVerb: "shall establish",
    applicability: { entities: ["DNS", "TLD", "CLOUD", "DC", "CDN", "MSP", "MSSP", "ONLINE_PLATFORM", "TRUST"] },
    evidenceTypes: ["Vulnerability management policy", "Scanning reports", "Patch management records"],
    testProcedure: { method: "Review vulnerability management procedures, scanning frequency, and patch management metrics" },
    domain: "Security Operations",
    weight: 2,
  },
  {
    controlId: "CIR-2024-2690-9-1",
    sourceKey: "CIR_2024_2690",
    legalRef: "Article 9(1) CIR 2024/2690",
    clausePath: "CIR.Art.9.1",
    shortTitle: "Cybersecurity awareness and training programmes",
    obligationText: "Relevant entities shall ensure that all staff including management receive appropriate cybersecurity awareness training and are informed of relevant cyber threats.",
    obligationVerb: "shall ensure",
    applicability: { entities: ["DNS", "TLD", "CLOUD", "DC", "CDN", "MSP", "MSSP", "ONLINE_PLATFORM", "TRUST"] },
    evidenceTypes: ["Training programme", "Awareness materials", "Completion records", "Phishing test results"],
    testProcedure: { method: "Review cybersecurity awareness programme, verify staff training completion rates and phishing simulation results" },
    domain: "Governance",
    weight: 2,
  },
  {
    controlId: "CIR-2024-2690-10-1",
    sourceKey: "CIR_2024_2690",
    legalRef: "Article 10(1) CIR 2024/2690",
    clausePath: "CIR.Art.10.1",
    shortTitle: "Use of cryptography and encryption",
    obligationText: "Relevant entities shall establish and implement a policy on the use of cryptography, including encryption where appropriate, for the protection of data in transit and at rest.",
    obligationVerb: "shall establish",
    applicability: { entities: ["DNS", "TLD", "CLOUD", "DC", "CDN", "MSP", "MSSP", "ONLINE_PLATFORM", "TRUST"] },
    evidenceTypes: ["Cryptography policy", "Encryption implementation records", "Key management procedure"],
    testProcedure: { method: "Review cryptography policy, verify encryption for data at rest and in transit, review key management" },
    domain: "Security Operations",
    weight: 2,
  },
  {
    controlId: "CIR-2024-2690-11-1",
    sourceKey: "CIR_2024_2690",
    legalRef: "Article 11(1) CIR 2024/2690",
    clausePath: "CIR.Art.11.1",
    shortTitle: "Access control policies and procedures",
    obligationText: "Relevant entities shall establish and implement access control policies based on business and security requirements, including least privilege, separation of duties and role-based access.",
    obligationVerb: "shall establish",
    applicability: { entities: ["DNS", "TLD", "CLOUD", "DC", "CDN", "MSP", "MSSP", "ONLINE_PLATFORM", "TRUST"] },
    evidenceTypes: ["Access control policy", "Access review records", "Privileged access management"],
    testProcedure: { method: "Review access control policy, verify least privilege implementation, review periodic access reviews" },
    domain: "Access Control",
    weight: 2,
  },
  {
    controlId: "CIR-2024-2690-11-2",
    sourceKey: "CIR_2024_2690",
    legalRef: "Article 11(2) CIR 2024/2690",
    clausePath: "CIR.Art.11.2",
    shortTitle: "Multi-factor authentication",
    obligationText: "Relevant entities shall implement multi-factor authentication for access to their network and information systems, in particular for remote access and access to critical systems.",
    obligationVerb: "shall implement",
    applicability: { entities: ["DNS", "TLD", "CLOUD", "DC", "CDN", "MSP", "MSSP", "ONLINE_PLATFORM", "TRUST"] },
    evidenceTypes: ["MFA deployment records", "Authentication policy", "Remote access procedures"],
    testProcedure: { method: "Verify MFA is deployed for remote access and critical systems, review authentication mechanisms" },
    domain: "Access Control",
    weight: 3,
  },
  {
    controlId: "CIR-2024-2690-12-1",
    sourceKey: "CIR_2024_2690",
    legalRef: "Article 12(1) CIR 2024/2690",
    clausePath: "CIR.Art.12.1",
    shortTitle: "Asset management and inventory",
    obligationText: "Relevant entities shall maintain an inventory of assets, including hardware, software, data and network components, relevant to the security of their network and information systems.",
    obligationVerb: "shall maintain",
    applicability: { entities: ["DNS", "TLD", "CLOUD", "DC", "CDN", "MSP", "MSSP", "ONLINE_PLATFORM", "TRUST"] },
    evidenceTypes: ["Asset register", "CMDB", "Network diagrams", "Data classification"],
    testProcedure: { method: "Review asset inventory completeness, verify regular updates and data classification" },
    domain: "Security Operations",
    weight: 2,
  },
  {
    controlId: "CIR-2024-2690-13-1",
    sourceKey: "CIR_2024_2690",
    legalRef: "Article 13(1) CIR 2024/2690",
    clausePath: "CIR.Art.13.1",
    shortTitle: "Security effectiveness assessment and testing",
    obligationText: "Relevant entities shall regularly assess the effectiveness of their cybersecurity risk-management measures including through vulnerability assessments and penetration testing.",
    obligationVerb: "shall assess",
    applicability: { entities: ["DNS", "TLD", "CLOUD", "DC", "CDN", "MSP", "MSSP", "ONLINE_PLATFORM", "TRUST"] },
    evidenceTypes: ["Penetration test reports", "Vulnerability assessment results", "Security audit findings"],
    testProcedure: { method: "Review latest pen test and vulnerability assessment results, verify regular testing schedule" },
    domain: "Risk Management",
    weight: 2,
  },
];

export async function seedAtomicControls(): Promise<void> {
  const existingControls = await storage.getAllAtomicControls();
  if (existingControls.length > 0) {
    console.log(`Atomic controls already seeded (${existingControls.length} controls found). Skipping.`);
    return;
  }

  console.log("Seeding atomic controls library...");

  const nis2Source = await storage.createLegalSource({
    key: "NIS2_2022_2555",
    title: "Directive (EU) 2022/2555 (NIS2 Directive)",
    url: "https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32022L2555",
    version: "2022-12-14",
  });

  const cirSource = await storage.createLegalSource({
    key: "CIR_2024_2690",
    title: "Commission Implementing Regulation (EU) 2024/2690",
    url: "https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=OJ:L_202402690",
    version: "2024-10-17",
  });

  let createdCount = 0;
  const allControls = [...NIS2_CONTROLS, ...CIR_CONTROLS];

  for (const ctrl of allControls) {
    await storage.createAtomicControl({
      controlId: ctrl.controlId,
      sourceKey: ctrl.sourceKey,
      legalRef: ctrl.legalRef,
      clausePath: ctrl.clausePath,
      shortTitle: ctrl.shortTitle,
      obligationText: ctrl.obligationText,
      obligationVerb: ctrl.obligationVerb || null,
      applicability: ctrl.applicability,
      evidenceTypes: ctrl.evidenceTypes,
      testProcedure: ctrl.testProcedure,
      domain: ctrl.domain,
      weight: ctrl.weight,
    });
    createdCount++;
  }

  const crypto = await import("crypto");
  const hash = crypto.createHash("sha256").update(JSON.stringify(allControls)).digest("hex").slice(0, 16);

  await storage.createControlPackVersion({
    sourceKey: "NIS2_2022_2555",
    generator: "atomic-seed.ts v1.0",
    hash: hash,
    controlCount: NIS2_CONTROLS.length,
    notes: "Initial NIS2 atomic controls from Articles 20-29",
  });

  await storage.createControlPackVersion({
    sourceKey: "CIR_2024_2690",
    generator: "atomic-seed.ts v1.0",
    hash: hash,
    controlCount: CIR_CONTROLS.length,
    notes: "Initial CIR 2024/2690 atomic controls from Articles 3-13",
  });

  console.log(`Seeded ${createdCount} atomic controls (${NIS2_CONTROLS.length} NIS2 + ${CIR_CONTROLS.length} CIR)`);
}
